[build]
  command = "npm run build"
  publish = "dist-ai/ai/dist-ai"  # ✅ Target the innermost build folder
  environment = {
    NODE_VERSION = "18",
    VITE_APP_VERSION = "1.0.0",
    VITE_DEPLOYMENT_ENV = "production"
  }

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(), camera=(), microphone=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net; font-src 'self' https://fonts.gstatic.com https://cdn.jsdelivr.net; img-src 'self' data: blob:; connect-src 'self' https://api.openai.com https://*.firebaseio.com https://*.googleapis.com;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Subdomain Redirect (ai.dawntasy.com → dawntasy.com/ai)
[[redirects]]
  from = "https://ai.dawntasy.com/*"
  to = "https://dawntasy.com/ai/:splat"
  status = 200
  force = true

# Cache Optimization
[[headers]]
  for = "/ai/assets/*.{js,css,woff2}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/ai/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/ai/assets/*"
  [headers.values]
    X-DNS-Prefetch-Control = "on"

# Vue Router Redirects (MUST BE LAST)
[[redirects]]
  from = "/ai/*"
  to = "/ai/index.html"
  status = 200
  force = true