# ✅ BUILD CONFIGURATION
[build]
  command = "npm run build"
  publish = "ai/dist"  # ✅ Change from "ai" to "ai/dist" because Vite builds into "dist"

# ✅ ENVIRONMENT VARIABLES
[build.environment]
  NODE_VERSION = "18"
  VITE_APP_VERSION = "1.0.0"
  VITE_DEPLOYMENT_ENV = "production"

# ✅ REDIRECTS FOR VUE ROUTER
[[redirects]]
  from = "/ai/*"
  to = "/ai/index.html"
  status = 200
  force = true

# ✅ SECURITY HEADERS
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(), camera=(), microphone=()"
    Content-Security-Policy = "default-src 'self'; 
                               script-src 'self' 'unsafe-inline'; 
                               style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; 
                               font-src 'self' https://fonts.gstatic.com; 
                               img-src 'self' data: blob:; 
                               connect-src 'self' https://api.openai.com https://*.firebaseio.com https://*.googleapis.com;"

# ✅ CACHE OPTIMIZATION
[[headers]]
  for = "/assets/*.{js,css,woff2}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, stale-while-revalidate=86400"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/api/*.json"
  [headers.values]
    Cache-Control = "public, max-age=86400, must-revalidate"

[[headers]]
  for = "/images/*.{png,jpg,svg}"
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"

[[headers]]
  for = "/*.{js,css}"
  [headers.values]
    X-DNS-Prefetch-Control = "on"
